// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for forge_id columns. */
export type ForgeId = number & { __brand: 'ForgeId' };

/** Represents the table public.forges */
export default interface ForgeTable {
  forge_id: ColumnType<ForgeId, ForgeId, ForgeId>;

  display_name: ColumnType<string, string, string>;
}

export type Forge = Selectable<ForgeTable>;

export type NewForge = Insertable<ForgeTable>;

export type ForgeUpdate = Updateable<ForgeTable>;
