// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for forge_id columns. */
export type ForgeId = number & { __brand: 'ForgeId' };

/** Represents the table public.forges */
export default interface ForgesTable {
  forge_id: ColumnType<ForgeId, ForgeId, ForgeId>;

  display_name: ColumnType<string, string, string>;
}

export type Forges = Selectable<ForgesTable>;

export type NewForges = Insertable<ForgesTable>;

export type ForgesUpdate = Updateable<ForgesTable>;
