// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { UserId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Represents the table public.forge_access_tokens */
export default interface ForgeAccessTokensTable {
  user_id: ColumnType<UserId, UserId, UserId>;

  access_token: ColumnType<Buffer, Buffer, Buffer>;

  access_token_expires_at: ColumnType<Date, Date | string, Date | string>;

  refresh_token: ColumnType<Buffer, Buffer, Buffer>;

  refresh_token_expires_at: ColumnType<Date, Date | string, Date | string>;
}

export type ForgeAccessTokens = Selectable<ForgeAccessTokensTable>;

export type NewForgeAccessTokens = Insertable<ForgeAccessTokensTable>;

export type ForgeAccessTokensUpdate = Updateable<ForgeAccessTokensTable>;
