// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { WorkflowRunId } from './WorkflowRuns';
import type { default as JobRunStatus } from './JobRunStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for job_run_id columns. */
export type JobRunId = number & { __brand: 'JobRunId' };

/** Represents the table public.job_runs */
export default interface JobRunTable {
  workflow_run_id: ColumnType<WorkflowRunId, WorkflowRunId, WorkflowRunId>;

  job_run_id: ColumnType<JobRunId, JobRunId, JobRunId>;

  name: ColumnType<string, string, string>;

  status: ColumnType<JobRunStatus, JobRunStatus, JobRunStatus>;

  queued_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  started_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  finished_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  source_file: ColumnType<string | null, string | null, string | null>;

  source_position: ColumnType<number | null, number | null, number | null>;
}

export type JobRun = Selectable<JobRunTable>;

export type NewJobRun = Insertable<JobRunTable>;

export type JobRunUpdate = Updateable<JobRunTable>;
