// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { WorkflowRunId } from './WorkflowRuns';
import type { JobRunId } from './JobRuns';
import type { default as JobRunStepStatus } from './JobRunStepStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.job_run_steps */
export type JobRunStepsStepIndex = number & { __brand: 'public.job_run_steps' };

/** Represents the table public.job_run_steps */
export default interface JobRunStepTable {
  workflow_run_id: ColumnType<WorkflowRunId, WorkflowRunId, WorkflowRunId>;

  job_run_id: ColumnType<JobRunId, JobRunId, JobRunId>;

  step_index: ColumnType<JobRunStepsStepIndex, JobRunStepsStepIndex, JobRunStepsStepIndex>;

  started_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  finished_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  exit_code: ColumnType<number | null, number | null, number | null>;

  status: ColumnType<JobRunStepStatus, JobRunStepStatus | undefined, JobRunStepStatus>;

  name: ColumnType<string, string, string>;
}

export type JobRunStep = Selectable<JobRunStepTable>;

export type NewJobRunStep = Insertable<JobRunStepTable>;

export type JobRunStepUpdate = Updateable<JobRunStepTable>;
