// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.job_run_step_status */
enum JobRunStepStatus {
  incomplete = 'incomplete',
  skipped_condition = 'skipped_condition',
  skipped_prerequisite = 'skipped_prerequisite',
  cancelled = 'cancelled',
  succeeded = 'succeeded',
  failed = 'failed',
  timed_out = 'timed_out',
};

export default JobRunStepStatus;
