// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.migrations */
export type MigrationsId = number & { __brand: 'public.migrations' };

/** Represents the table public.migrations */
export default interface MigrationsTable {
  id: ColumnType<MigrationsId, MigrationsId, MigrationsId>;

  name: ColumnType<string, string, string>;

  hash: ColumnType<string, string, string>;

  executed_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Migrations = Selectable<MigrationsTable>;

export type NewMigrations = Insertable<MigrationsTable>;

export type MigrationsUpdate = Updateable<MigrationsTable>;
