// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { RepoId } from './Repositories';
import type { default as TriggerEventType } from './TriggerEventType';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for pipeline_run_id columns. */
export type PipelineRunId = bigint & { __brand: 'PipelineRunId' };

/** Represents the table public.pipeline_runs */
export default interface PipelineRunTable {
  pipeline_run_id: ColumnType<PipelineRunId, PipelineRunId | undefined, PipelineRunId>;

  repo_id: ColumnType<RepoId, RepoId, RepoId>;

  triggered_at: ColumnType<Date, Date | string, Date | string>;

  trigger_event_type: ColumnType<TriggerEventType, TriggerEventType, TriggerEventType>;

  commit_hash: ColumnType<string, string, string>;

  ref: ColumnType<string, string, string>;

  commit_message: ColumnType<string, string, string>;

  pr_short_human_id: ColumnType<string | null, string | null, string | null>;
}

export type PipelineRun = Selectable<PipelineRunTable>;

export type NewPipelineRun = Insertable<PipelineRunTable>;

export type PipelineRunUpdate = Updateable<PipelineRunTable>;
