// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as WorkflowRunTable } from './WorkflowRuns';
import type { default as UserTable } from './Users';
import type { default as JobRunStepTable } from './JobRunSteps';
import type { default as PipelineRunTable } from './PipelineRuns';
import type { default as ForgeAccessTokenTable } from './ForgeAccessTokens';
import type { default as RepositoryTable } from './Repositories';
import type { default as ForgeTable } from './Forges';
import type { default as JobRunTable } from './JobRuns';

export default interface PublicSchema {
  workflow_runs: WorkflowRunTable;

  users: UserTable;

  job_run_steps: JobRunStepTable;

  pipeline_runs: PipelineRunTable;

  forge_access_tokens: ForgeAccessTokenTable;

  repositories: RepositoryTable;

  forges: ForgeTable;

  job_runs: JobRunTable;
}
