// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UsersTable } from './Users';
import type { default as MigrationsTable } from './Migrations';
import type { default as ForgeAccessTokensTable } from './ForgeAccessTokens';
import type { default as RepositoriesTable } from './Repositories';
import type { default as ForgesTable } from './Forges';

export default interface PublicSchema {
  users: UsersTable;

  migrations: MigrationsTable;

  forge_access_tokens: ForgeAccessTokensTable;

  repositories: RepositoriesTable;

  forges: ForgesTable;
}
