// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as UserTable } from './Users';
import type { default as ForgeAccessTokenTable } from './ForgeAccessTokens';
import type { default as RepositoryTable } from './Repositories';
import type { default as ForgeTable } from './Forges';

export default interface PublicSchema {
  users: UserTable;

  forge_access_tokens: ForgeAccessTokenTable;

  repositories: RepositoryTable;

  forges: ForgeTable;
}
