// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ForgeId } from './Forges';
import type { UserId } from './Users';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for repo_id columns. */
export type RepoId = number & { __brand: 'RepoId' };

/** Represents the table public.repositories */
export default interface RepositoriesTable {
  repo_id: ColumnType<RepoId, RepoId | undefined, RepoId>;

  forge_id: ColumnType<ForgeId, ForgeId, ForgeId>;

  forge_repo_id: ColumnType<string, string, string>;

  owner_id: ColumnType<UserId, UserId, UserId>;

  repo_name: ColumnType<string, string, string>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;

  webhook_secret: ColumnType<string | null, string | null, string | null>;
}

export type Repositories = Selectable<RepositoriesTable>;

export type NewRepositories = Insertable<RepositoriesTable>;

export type RepositoriesUpdate = Updateable<RepositoriesTable>;
