// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.trigger_event_type */
enum TriggerEventType {
  push = 'push',
  pull_request = 'pull_request',
};

export default TriggerEventType;
