// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ForgeId } from './Forges';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for user_id columns. */
export type UserId = number & { __brand: 'UserId' };

/** Represents the table public.users */
export default interface UserTable {
  user_id: ColumnType<UserId, UserId | undefined, UserId>;

  forge_id: ColumnType<ForgeId, ForgeId, ForgeId>;

  forge_user_id: ColumnType<string, string, string>;

  forge_username: ColumnType<string, string, string>;
}

export type User = Selectable<UserTable>;

export type NewUser = Insertable<UserTable>;

export type UserUpdate = Updateable<UserTable>;
