// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.workflow_run_status */
enum WorkflowRunStatus {
  incomplete = 'incomplete',
  cancelled = 'cancelled',
  succeeded = 'succeeded',
  failed = 'failed',
  timed_out = 'timed_out',
};

export default WorkflowRunStatus;
