// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { PipelineRunId } from './PipelineRuns';
import type { default as WorkflowRunStatus } from './WorkflowRunStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Branded type for workflow_run_id columns. */
export type WorkflowRunId = bigint & { __brand: 'WorkflowRunId' };

/** Represents the table public.workflow_runs */
export default interface WorkflowRunTable {
  workflow_run_id: ColumnType<WorkflowRunId, WorkflowRunId | undefined, WorkflowRunId>;

  pipeline_run_id: ColumnType<PipelineRunId, PipelineRunId, PipelineRunId>;

  status: ColumnType<WorkflowRunStatus, WorkflowRunStatus, WorkflowRunStatus>;
}

export type WorkflowRun = Selectable<WorkflowRunTable>;

export type NewWorkflowRun = Insertable<WorkflowRunTable>;

export type WorkflowRunUpdate = Updateable<WorkflowRunTable>;
