# Compose file to launch the necessary services for running the CORNCRAKECI test suite.

services:
  corncrakeci-test-postgres:
    image: postgres:17-alpine

    # Turn off crash-safety features (for speed)
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c log_destination=stderr
      -c log_statement=all
      -c log_duration=on
      -c log_min_duration_statement=0
      -c log_lock_waits=on
      -c deadlock_timeout=200ms
      -c log_line_prefix='%m [%p] %u@%d '

    # Don't persist the data (for speed)
    tmpfs:
      - /var/lib/postgresql/data

    environment:
      POSTGRES_USER: corncrakecitest
      POSTGRES_PASSWORD: corncrakecitest
      POSTGRES_DB: corncrakecitest

    ports:
      # Remap port to 15432 to not conflict with other database.
      - "15432:5432"
