CREATE TABLE forges (
    forge_id INTEGER PRIMARY KEY NOT NULL,
    display_name TEXT NOT NULL,          -- e.g gitea
    base_url TEXT NOT NULL               -- API base URL
);


CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forge_id INT NOT NULL REFERENCES forges(forge_id) ON DELETE CASCADE,
    forge_user_id TEXT NOT NULL,
    access_token TEXT NOT NULL,                                   -- OAuth access token
    token_expires_at TIMESTAMPTZ,
    UNIQUE(forge_id, forge_user_id)                             -- Only one account per forge per user
);

-- Repos from forges
CREATE TABLE repositories (
    repo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forge_id INT NOT NULL REFERENCES forges(forge_id) ON DELETE CASCADE,
    forge_repo_id TEXT NOT NULL,
    owner_id INT REFERENCES users(user_id) NOT NULL,
    repo_name TEXT NOT NULL,
    description TEXT,
    clone_url TEXT NOT NULL,
    ssh_url TEXT,
    html_url TEXT,                                                  -- might be useful for linking to the repo in our frontend
    is_private BOOLEAN DEFAULT FALSE,
    default_branch TEXT DEFAULT 'main',                     -- need to know the main branch to trigger builds
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(forge_id, forge_repo_id)
);


INSERT INTO forges (forge_id, display_name, base_url)
VALUES (0, 'gitea', 'http://localhost:3000');

INSERT INTO users (forge_id, forge_user_id, access_token)
VALUES (0, 'testuser', 'dummy_token');


INSERT INTO repositories (forge_id, forge_repo_id, owner_id, repo_name, description, clone_url, ssh_url, html_url, is_private)
VALUES
    (0, '1', 1, 'my-awesome-project', 'A sample project for testing MOLCI',
    'http://localhost:3000/testuser/my-awesome-project.git',
    'git@localhost:testuser/my-awesome-project.git',
    'http://localhost:3000/testuser/my-awesome-project', false),
    
    (0, '2', 1,'molci-frontend', 'Frontend for MOLCI CI system',
    'http://localhost:3000/testuser/molci-frontend.git',
    'git@localhost:testuser/molci-frontend.git',
    'http://localhost:3000/testuser/molci-frontend', false);
