-- A forge is a service where repositories are stored.
CREATE TABLE forges (
	-- A unique ID that represents this forge in this installation.
    forge_id INTEGER PRIMARY KEY NOT NULL,
    -- A human-readable name for the forge.
    -- e.g. 'Gitea'
    display_name TEXT NOT NULL
);

-- Our local store of users, who log in via a forge.
CREATE TABLE users (
	-- A unique ID that represents this user in this installation.
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The ID of the forge that this user is from.
    forge_id INT NOT NULL REFERENCES forges(forge_id) ON DELETE CASCADE,
    -- The ID of the user *in the forge*.
    -- Since we can't assume an ID format, we store in text.
    forge_user_id TEXT NOT NULL,
    -- The access token, used for making requests as this user to the forge.
    access_token TEXT NOT NULL,
    -- When the access token expires.
    -- NULL means the access token is not valid.
    token_expires_at TIMESTAMPTZ,
    -- Only one account per forge per user
    UNIQUE (forge_id, forge_user_id)
);

-- Repos from forges
CREATE TABLE repositories (
    repo_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forge_id INT NOT NULL REFERENCES forges(forge_id) ON DELETE CASCADE,
    forge_repo_id TEXT NOT NULL,
    owner_id INT REFERENCES users(user_id) NOT NULL,
    repo_name TEXT NOT NULL,
    description TEXT,
    clone_url TEXT NOT NULL,
    ssh_url TEXT,
    html_url TEXT,                                                  -- might be useful for linking to the repo in our frontend
    is_private BOOLEAN DEFAULT FALSE,
    default_branch TEXT DEFAULT 'main',                     -- need to know the main branch to trigger builds
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(forge_id, forge_repo_id)
);
