
-- Status of a workflow
CREATE TYPE workflow_run_status AS ENUM (
    -- The workflow hasn't finished yet.
    -- Note that having this status does not guarantee it will be completed in the future;
    -- the workflow could be interrupted at runtime and never completed.
    --
    -- The actual pending state in-memory should be consulted.
    'incomplete',
    -- The workflow was cancelled explicitly.
    'cancelled',
    -- The workflow succeeded.
    'succeeded',
    -- The workflow failed.
    'failed',
    -- The workflow failed by running out of time.
    'timed_out'
);

-- Status of a job
CREATE TYPE job_run_status AS ENUM (
    -- The job hasn't finished yet.
    -- When a job is in this state, it means either:
    -- a) the job has been abandoned because the CI system crashed/restarted/etc; or
    -- b) the job is currently in the scheduler or runner,
    --    waiting for dependencies, waiting to be scheduled or being run.
    --
    -- The actual state in-memory should be consulted.
    'incomplete',
    -- The job was skipped because of a condition for execution not being
    -- satisfied.
    'skipped_condition',
    -- The job was skipped because its dependency jobs were not in the
    -- expected state. (e.g. a dependency job failed)
    'skipped_prerequisite',
    -- The job was cancelled explicitly.
    'cancelled',
    -- The job succeeded.
    'succeeded',
    -- The job failed.
    'failed',
    -- The job failed by running out of time.
    'timed_out'
);

-- Status of an individual step within a job
CREATE TYPE job_run_step_status AS ENUM (
    -- The step hasn't finished yet.
    'incomplete',
    -- The step was skipped because a condition for execution was not satisfied.
    'skipped_condition',
    -- The step was skipped because a prior step in the job failed or was skipped.
    'skipped_prerequisite',
    -- The step was cancelled explicitly.
    'cancelled',
    -- The step succeeded.
    'succeeded',
    -- The step failed.
    'failed',
    -- The step failed by running out of time.
    'timed_out'
);

-- Kind of event that triggered an event
CREATE TYPE trigger_event_type AS ENUM (
    'push',
    'pull_request'
);

-- A pipeline run represents the act of a single trigger event causing one or more
-- workflows to be planned and executed.
--
-- Conceptually, a pipeline run is the container for several independent workflow runs.
CREATE TABLE pipeline_runs (
    -- A unique ID that is the primary identifier for the pipeline run.
    pipeline_run_id BIGINT NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,

    -- The repository that this run belongs to.
    repo_id INT NOT NULL REFERENCES repositories(repo_id)
        ON DELETE CASCADE,

    -- The instant at which the pipeline run was triggered.
    triggered_at TIMESTAMPTZ NOT NULL,

    -- What kind of event triggered the pipeline run
    trigger_event_type trigger_event_type NOT NULL,

    -- the hash of the commit that is being tested
    commit_hash TEXT NOT NULL,

    -- the ref that is being tested
    ref TEXT NOT NULL,
    
    -- the message associated with a commit, useful for identifying pipeline runs in UI
    commit_message TEXT NOT NULL,

    -- For pull requests: the short human ID (typically a number) of the PR that triggered the pipeline run
    -- For everything else: NULL
    pr_short_human_id TEXT
);

-- Needed to satisfy `repo_id` backreference checks and to make it easy to find
-- runs by repo, ordered by most recent first
CREATE INDEX ON pipeline_runs (repo_id, triggered_at);


-- The individual unit of planning, or at least the container within which inter-job dependencies
-- are possible.
CREATE TABLE workflow_runs (
    -- The pipeline run that contains this workflow run.
    pipeline_run_id BIGINT NOT NULL REFERENCES pipeline_runs(pipeline_run_id)
        ON DELETE CASCADE,

    -- A unique ID that is the primary identifier for the workflow run.
    workflow_run_id BIGINT NOT NULL PRIMARY KEY
        GENERATED BY DEFAULT AS IDENTITY,

    -- The overall status of the workflow
    status workflow_run_status NOT NULL
);

-- Needed to satisfy foreign key constraint backreference checks and to make it easy
-- to find workflow runs after you've navigated into the pipeline run.
CREATE INDEX ON workflow_runs (pipeline_run_id);


-- The individual unit of scheduling.
CREATE TABLE job_runs (
    -- The workflow run that contains this job run.
    workflow_run_id BIGINT NOT NULL REFERENCES workflow_runs(workflow_run_id)
        ON DELETE CASCADE,

    -- The ID of this job run within the workflow run.
    -- Only unique within this workflow run.
    job_run_id SMALLINT NOT NULL,

    -- TODO What exactly should this mean?
    name TEXT NOT NULL,

    -- The status of this job.
    status job_run_status NOT NULL,

    -- The instant at which the job was ready to be picked up
    queued_at TIMESTAMPTZ,

    -- The instant at which the job was picked up by a runner
    started_at TIMESTAMPTZ,

    -- The instant at which the job was finished by the runner
    finished_at TIMESTAMPTZ,

    -- Source file containing the job definition, if there is one.
    -- Expected to be unset for internal jobs.
    source_file TEXT,

    -- Source line within `source_file` at which the job is defined, if there is one.
    -- Expected to be unset for internal jobs.
    source_position INT,

    PRIMARY KEY (workflow_run_id, job_run_id)
);

-- Individual steps within a job.
CREATE TABLE job_run_steps (
    -- The workflow run that contains this job run.
    workflow_run_id BIGINT NOT NULL REFERENCES workflow_runs(workflow_run_id)
        ON DELETE CASCADE,

    -- The ID of this job run within the workflow run.
    -- Only unique within this workflow run.
    job_run_id SMALLINT NOT NULL,

    step_index SMALLINT NOT NULL,

    started_at TIMESTAMPTZ,

    finished_at TIMESTAMPTZ,

    exit_code INT,

    status job_run_step_status NOT NULL DEFAULT 'incomplete',

    -- TODO Store richer information (TODO Open issue if can't figure out what)

    FOREIGN KEY (workflow_run_id, job_run_id) REFERENCES job_runs(workflow_run_id, job_run_id),

    PRIMARY KEY (workflow_run_id, job_run_id, step_index)
);
