when:
  - event: push
    branch: [main, dev]
  - event: pull_request

labels:
  platform: linux/amd64

steps:
  - name: postgres
    detach: true
    image: postgres:17
    environment:
      POSTGRES_USER: molcitest
      POSTGRES_PASSWORD: molcitest
      POSTGRES_DB: molcitest
    entrypoint:
      # https://github.com/docker-library/postgres/blob/2925b19f45ceeb8ab8488eec226f2736abf297e1/18/trixie/Dockerfile#L197
      - docker-entrypoint.sh
      - postgres
      # In future, make faster by turning off fsync etc.
      # For now, we are trying to reproduce a bug with statement logging,
      # and don't want to change the test environment more than necessary.
      # - "-c"
      # - "fsync=off"
      # - "-c"
      # - "synchronous_commit=off"
      # - "-c"
      # - "full_page_writes=off"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_duration=on"
      - "-c"
      - "log_min_duration_statement=0"
      - "-c"
      - "log_lock_waits=on"
      - "-c"
      - "deadlock_timeout=200ms"
      - "-c"
      - "log_line_prefix=%m [%p] %u@%d "

  - name: server
    image: guergeiro/pnpm:22-10-slim
    environment:
      NODE_ENV: test
      DB_URI: postgresql://molcitest:molcitest@postgres:5432/molcitest

    commands:
      - cd server
      - pnpm install --frozen-lockfile

      - pnpm run generate

      - touch .env

      - pnpm run check
      - pnpm run build

      - pnpm exec biome check

      - pnpm run test


  # Additionally notify GitHub of the CI status (since our pipeline is wired up
  # to Gitea, but the repo is mirrored to GitHub in realtime)
  - name: notify-github-success
    image: curlimages/curl:latest
    commands:
      - |
        curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/CaptOrb/molci/statuses/$${CI_COMMIT_SHA} \
          -d "{\"state\":\"success\",\"target_url\":\"$${CI_PIPELINE_URL}\",\"description\":\"All checks passed\",\"context\":\"Woodpecker CI\"}"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      status: [success]

  - name: notify-github-failure
    image: curlimages/curl:latest
    commands:
      - |
        curl -L -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/CaptOrb/molci/statuses/$${CI_COMMIT_SHA} \
          -d "{\"state\":\"failure\",\"target_url\":\"$${CI_PIPELINE_URL}\",\"description\":\"Build failed\",\"context\":\"Woodpecker CI\"}"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      status: [failure]
